export const Users = [
    {
        id: 1,
        profilePicture: "person/205128_adapted_landscape_2560x2560.jpg",
        username: "Omni Johnson",
    },
    {
        id: 2,
        profilePicture: "person/realcurate2_pic.jpg",
        username: "John Anosike",
    },
    {
        id: 3,
        profilePicture: "person/205128_adapted_landscape_2560x2560.jpg",
        username: "Elon Musk",
    },
    {
        id: 4,
        profilePicture: "person/205128_adapted_landscape_2560x2560.jpg",
        username: "Stallion James",
    },
    {
        id: 5,
        profilePicture: "person/205128_adapted_landscape_2560x2560.jpg",
        username: "Adoni Creed",
    },
    {
        id: 6,
        profilePicture: "person/205128_adapted_landscape_2560x2560.jpg",
        username: "LeBron James",
    },
    {
        id: 7,
        profilePicture: "person/205128_adapted_landscape_2560x2560.jpg",
        username: "Culprit Man",
    },
    {
        id: 8,
        profilePicture: "person/205128_adapted_landscape_2560x2560.jpg",
        username: "John Wick",
    },
    {
        id: 9,
        profilePicture: "person/205128_adapted_landscape_2560x2560.jpg",
        username: "Mason James",
    },
    {
        id: 10,
        profilePicture: "person/205128_adapted_landscape_2560x2560.jpg",
        username: "Jonny Creed",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Una dey craze",
        photo: "person/205128_adapted_landscape_2560x2560.jpg",
        date: "2000 mins ago",
        userId: 1,
        like: 32,
        comment: 10,
    },
    {
        id: 2,
        desc: "Make una no vex",
        photo: "person/58824-black-hacker-wallpaper-top-free-black-hacker-background.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 10000000,
        comment: 600,
    },
    {
        id: 3,
        desc: "sorry na",
        photo: "person/icons8-like-94.png",
        date: "18.5 mins ago",
        userId: 3,
        like: 32,
        comment: 10,
    },
    {
        id: 4,
        desc: "hey peeps i jus wan greet",
        photo: "person/realcurate2_pic.jpg",
        date: "1500 mins ago",
        userId: 4,
        like: 332,
        comment: 1050,
    },
    {
        id: 5,
        desc: "No Wam",
        photo: "person/Monkey With Headset.jpg",
        date: "5 yrs ago",
        userId: 5,
        like: 32,
        comment: 10,
    },
    {
        id: 6,
        desc: "Una dey craze",
        photo: "person/205128_adapted_landscape_2560x2560.jpg",
        date: "15 mins ago",
        userId: 6,
        like: 32,
        comment: 10,
    },
    {
        id: 7,
        desc: "Una dey craze",
        photo: "person/205128_adapted_landscape_2560x2560.jpg",
        date: "15 mins ago",
        userId: 7,
        like: 32,
        comment: 10,
    },
    {
        id: 8,
        desc: "Una dey craze",
        photo: "person/205128_adapted_landscape_2560x2560.jpg",
        date: "15 mins ago",
        userId: 8,
        like: 32,
        comment: 10,
    },
    {
        id: 9,
        desc: "Una dey craze",
        photo: "person/205128_adapted_landscape_2560x2560.jpg",
        date: "15 mins ago",
        userId: 9,
        like: 32,
        comment: 10,
    },
    {
        id: 10,
        desc: "Una dey craze",
        photo: "person/205128_adapted_landscape_2560x2560.jpg",
        date: "15 mins ago",
        userId: 10,
        like: 32,
        comment: 10,
    },
];